# Generated by Django 3.2.5 on 2021-07-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('committees', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('term', models.IntegerField()),
                ('incentive_equity_award', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('term', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('at_will', models.BooleanField()),
                ('at_will_exceptions', models.CharField(max_length=500)),
                ('incentive_equity_award', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EquityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_entity', models.CharField(max_length=100)),
                ('equity_class_type', models.CharField(max_length=100)),
                ('number_authorized', models.IntegerField()),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EquityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_entity', models.CharField(max_length=100)),
                ('equity_class_type', models.CharField(max_length=100)),
                ('beneficial_holder', models.CharField(max_length=100)),
                ('number_issued', models.IntegerField()),
                ('date_of_issuance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('state_of_formation', models.CharField(max_length=2)),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('officer', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('term', models.IntegerField()),
                ('incentive_equity_award', models.CharField(max_length=500)),
            ],
        ),
    ]
