# Generated by Django 3.2.5 on 2021-07-04 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_directorrelation_employmentrelation_equityclass_equitytoken_legalentity_officerrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitytoken',
            name='beneficial_holder',
        ),
        migrations.AddField(
            model_name='equitytoken',
            name='legal_entity_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_holder', to='myapi.legalentity'),
        ),
        migrations.AddField(
            model_name='equitytoken',
            name='natural_person_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.naturalperson'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='entity_name',
            field=models.CharField(default='TEST NAME', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directorrelation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.legalentity'),
        ),
        migrations.AlterField(
            model_name='directorrelation',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.naturalperson'),
        ),
        migrations.AlterField(
            model_name='directorrelation',
            name='incentive_equity_award',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='directorrelation',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmentrelation',
            name='at_will_exceptions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employmentrelation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.naturalperson'),
        ),
        migrations.AlterField(
            model_name='employmentrelation',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.legalentity'),
        ),
        migrations.AlterField(
            model_name='employmentrelation',
            name='incentive_equity_award',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employmentrelation',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equityclass',
            name='issuing_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.legalentity'),
        ),
        migrations.AlterField(
            model_name='equitytoken',
            name='equity_class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.equityclass'),
        ),
        migrations.AlterField(
            model_name='equitytoken',
            name='issuing_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuing_entity', to='myapi.legalentity'),
        ),
        migrations.AlterField(
            model_name='officerrelation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.legalentity'),
        ),
        migrations.AlterField(
            model_name='officerrelation',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.naturalperson'),
        ),
    ]
