# Generated by Django 3.2.5 on 2021-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210704_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerrelation',
            name='incentive_equity_award',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
